### ISSUE TITLE
Missing source code

### ISSUE THREAD

**Issue by andregoiano** [BrAmaral/Omega-Project#1]
Just messing with you. Have you downloaded the desktop version of GitHub, though? Makes it much easier to synch up files to the repository.

**Comment by BrAmaral** [comment]
Heuheuehueh not yet bro, will do it right now!
Thanks for the heads up

**Comment by BrAmaral** [comment]
Script for Omega Project has been posted. I will add more stuff later tho.
Feel free to edit anything you want.
